name: multimodal-llm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - opencv
  - pillow
  - torchvision
  - pytorch
  - tqdm
  - jupyterlab
  - notebook
  - ipywidgets
  - scipy
  - h5py
  - ffmpeg
  - pip:
      - transformers>=4.31
      - accelerate
      - datasets
      - evaluate
      - timm
      - torchmetrics
      - sentencepiece
      - einops
      - qwen-vl-utils
      - openai
      - langchain
      - huggingface-hub
      - pyyaml
      - wandb
      - xformers
      - imageio
      - matplotlib-inline
      - clip-by-openai
      - diffusers
      - pytesseract
      - pycocotools
      - albumentations
      - multimodal-transformers
      - visual-bert
      - unstructured[image]